import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";
import RunningNews from "@/components/shared/running-news";
import Footer from "@/components/shared/footer";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
      <Header/>
        <main>
            {children}
        </main>
      <Footer/>
      </body>
    </html>
  );
}
